---

- name: grafana-install | Add centos repository
  template: src=grafana.repo.j2 dest=/etc/yum.repos.d/grafana.repo

- set_fact: grafana_release='grafana={{grafana_version}}'

- name: grafana-install | Install Grafana Release
  apt: name="{{grafana_release}}"
  when: grafana_version != "latest"
  notify:
    - grafana restart

- name: grafana-install | Install Grafana Latest
  apt: name="grafana"
  when: grafana_version == "latest"
  notify:
  - grafana restart
